import os
import shutil
from datetime import datetime
from pathlib import Path
from typing import Set

import pandas as pd
from tqdm import tqdm

from .readers import dcmtag2table


def list_files_in_directory(directory: str) -> Set[str]:
    """
    List all files in a directory and its subdirectories.

    :param directory: The directory to search for files.
    :return: A set of file paths.
    """
    file_paths = set()
    for root, _, files in tqdm(os.walk(directory)):
        for file in files:
            file_paths.add(os.path.join(root, file))
    return file_paths


def copy_files(df, column_name: str, folder2replace: str):
    """
    Copies files from source paths listed in a DataFrame to a destination path.
    The destination path is generated by replacing a matching directory segment
    in the source path with the same folder name appended with '_filtered'.

    Parameters:
    df (pandas.DataFrame): A DataFrame containing file paths.
    column_name (str): The name of the column in the DataFrame where file paths are stored.
    folder2replace (str): The folder name in the path to be replaced with 'folder2replace_filtered'.

    The function iterates over each file path in the specified DataFrame column, replaces the specified
    folder name in the path with 'folder2replace_filtered', creates the destination directory if it does
    not exist, and then copies the file to the new location.
    """
    for source_path in tqdm(df[column_name]):
        source = Path(source_path)
        parts = list(source.parts)
        try:
            folder_index = parts.index(folder2replace)
        except ValueError as exc:
            raise ValueError(
                f"Path '{source_path}' does not contain directory segment '{folder2replace}'"
            ) from exc

        parts[folder_index] = folder2replace + "_filtered"
        destination_path = str(Path(*parts))

        os.makedirs(os.path.dirname(destination_path), exist_ok=True)

        # Copy the file
        shutil.copy2(source_path, destination_path)


def remove_if_tag_contains(df, tag: str, list2remove: list):
    """
    Filters out rows in a DataFrame based on whether a specified column (tag) contains any of the substrings
    in a given list. This function is case-insensitive.

    Parameters:
    df (pandas.DataFrame): The DataFrame to be filtered.
    tag (str): The name of the column in the DataFrame to check for substrings.
    list2remove (list): A list of substrings. If the 'tag' column contains any of these substrings,
                        the corresponding row will be removed from the DataFrame.

    Returns:
    pandas.DataFrame: A DataFrame after removing rows where the 'tag' column contains any of the
                      substrings in 'list2remove'.

    The function iterates over each substring in 'list2remove' and removes rows from the DataFrame
    where the 'tag' column contains the substring. The search is case-insensitive.
    """
    for _substring in list2remove:
        df = df[~df[tag].str.contains(_substring, case=False, regex=False, na=False)]
    return df


def get_folder_size(path):
    total_size = 0
    for dirpath, _dirnames, filenames in os.walk(path):
        for f in tqdm(filenames):
            fp = os.path.join(dirpath, f)
            if os.path.exists(fp):
                total_size += os.path.getsize(fp)
    return total_size


def append_to_csv(file_path, data_dict):
    # Create a DataFrame from the dictionary
    new_row = pd.DataFrame([data_dict])

    # Check if the file exists
    if os.path.exists(file_path):
        # Read existing data
        df = pd.read_csv(file_path)
        # Concatenate the new data
        df = pd.concat([df, new_row], ignore_index=True)
    else:
        # Use the new row as the DataFrame
        df = new_row

    # Save to CSV
    df.to_csv(file_path, index=False)


def get_metrics(folder: str, output_file: str):
    list_of_tags = [
        "PatientID",
        "StudyInstanceUID",
        "SeriesInstanceUID",
        "SOPInstanceUID",
        "Modality",
        "PatientSex",
        "PatientAge",
    ]
    df = dcmtag2table(folder, list_of_tags)
    study_dd = df.drop_duplicates("StudyInstanceUID")
    patient_dd = df.drop_duplicates("PatientID")
    percentage_male = (
        0
        if patient_dd.empty
        else len(patient_dd[patient_dd["PatientSex"] == "M"]) / len(patient_dd)
    )

    summary = {
        "Timestamp": datetime.now().strftime("%m/%d/%Y, %H:%M:%S"),
        "Number of files": len(df),
        "Batch Size Bytes": get_folder_size(folder),
        "Number of patients": len(df["PatientID"].unique()),
        "Number of studies": len(df["StudyInstanceUID"].unique()),
        "Number of series": len(df["SeriesInstanceUID"].unique()),
        "Number of MRs": len(study_dd[study_dd["Modality"] == "MR"]),
        "Number of CTs": len(study_dd[study_dd["Modality"] == "CT"]),
        "Number of USs": len(study_dd[study_dd["Modality"] == "US"]),
        "Number of CRs": len(study_dd[study_dd["Modality"] == "CR"]),
        "Number of DXs": len(study_dd[study_dd["Modality"] == "DX"]),
        "Percentage of male": percentage_male,
    }
    append_to_csv(output_file, summary)
    return summary


def summary(df) -> None:
    print("Total unique values per column:")
    for _col in df.columns:
        print(f"{_col}: {len(df[_col].unique())!s}")
